### ISSUE TITLE
Вычистить рецепты крафтов до конца

### ISSUE THREAD

**Issue by TheShuEd** [crystallpunk-14/crystall-punk-14#12]
## Description

На текущий момент осталось около 10 рецептов крафтов из основной сосаки, которые так просто не удалить, т.к. они используются в интеграционных тестах.

Нужно изменить интеграционные тесты, чтобы они тестировали какие-то комплексные крафты уже наших, фентезийных штук.

**Comment by Deserty0** [comment]
> ## Description
> На текущий момент осталось около 10 рецептов крафтов из основной сосаки, которые так просто не удалить, т.к. они используются в интеграционных тестах.
> 
> Нужно изменить интеграционные тесты, чтобы они тестировали какие-то комплексные крафты уже наших, фентезийных штук.

для начала бы эти крафты добавить

**Comment by TheShuEd** [comment]
Сделано
![image](https://github.com/crystallpunk-14/crystall-punk-14/assets/96445749/e4f6c659-4f81-4337-8e49-f15e0e1a4a45)
