### ISSUE TITLE
Респрайт игровых персонажей 

### ISSUE THREAD

**Issue by Agoichi** [crystallpunk-14/crystall-punk-14#21]
Напоминаю. Мы хотим переделать наших челочелов под 3/4.
Тоесть так:
![image-10.png](https://github.com/crystallpunk-14/crystall-punk-14/assets/92464780/c1dc304a-12ff-4eb7-9967-dd4088f993c3)

![SS13Humans.png](https://github.com/crystallpunk-14/crystall-punk-14/assets/92464780/4fea562c-ddfd-43c3-bd11-4d479ecd5b16)

**Comment by TheShuEd** [comment]
https://github.com/crystallpunk-14/crystall-punk-14/pull/28
