### ISSUE TITLE
Importing characters issues

### ISSUE THREAD

**Issue by TheShuEd** [crystallpunk-14/crystall-punk-14#220]
> importing character from maintstream did not like the current setup lol

You can also sometimes see a similar problem, when first logging into the server, players sometimes have a standard human character. 

![image](https://github.com/crystallpunk-14/crystall-punk-14/assets/96445749/e2062b59-bfbb-4d70-a4f2-f835f5f522c3)

Maybe wizden issue!

**Comment by TheShuEd** [comment]
huh, upstream moment?

**Comment by Deserty0** [comment]
> huh, upstream moment?

idk
