### ISSUE TITLE
thaumaturgy and alchemy glasses use same sprite

### ISSUE THREAD

**Issue by TheShuEd** [crystallpunk-14/crystall-punk-14#244]
Damn it, I forgot to fix that.

**Comment by Jaraten** [comment]
Which path and name to record thaumaturgy glasses by?

**Comment by TheShuEd** [comment]
![image](https://github.com/crystallpunk-14/crystall-punk-14/assets/96445749/eded9117-dbc8-4a77-93b0-bce67ddd8168)
