### ISSUE TITLE
need resprite all wall

### ISSUE THREAD

**Issue by TheShuEd** [crystallpunk-14/crystall-punk-14#266]
in the image #265
по образу и подобию

**Comment by Jaraten** [comment]
I updated the wall template [tap](https://github.com/crystallpunk-14/crystallpunk-docs/blob/main/src/%D0%90%D1%80%D1%82-%D0%94%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD/%D0%A8%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD%D1%8B/Wall.aseprite)

**Comment by TheShuEd** [comment]
> I updated the wall template [tap](https://github.com/crystallpunk-14/crystallpunk-docs/blob/main/src/%D0%90%D1%80%D1%82-%D0%94%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD/%D0%A8%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD%D1%8B/Wall.aseprite)

есть ли еще неподнятые стены?

**Comment by Jaraten** [comment]
> > I updated the wall template [tap](https://github.com/crystallpunk-14/crystallpunk-docs/blob/main/src/%D0%90%D1%80%D1%82-%D0%94%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD/%D0%A8%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD%D1%8B/Wall.aseprite)
> 
> есть ли еще неподнятые стены?
Только земляная, которую ты хотел сам поднять, а ещё второй вариант кирпичной.
