### ISSUE TITLE
Localization helper needs fixes

### ISSUE THREAD

**Issue by Deserty0** [crystallpunk-14/crystall-punk-14#281]
## Description
Some funny prototypes cant be processed

**Reproduction**
run loc helper and open logs file

**Additional context**
I will fix it tomorrow

**Comment by TheShuEd** [comment]
```
YML-ERROR:
An error occurred during prototype processing ../../../Resources/Prototypes/_CP14/Entities\Objects\Weapons\Melee\base.yml, error - while parsing a block mapping
  in "<unicode string>", line 35, column 7:
          fix1:
          ^
expected <block end>, but found '<block mapping start>'
  in "<unicode string>", line 41, column 9:
            density: 10
            ^

```

**Comment by comasqw** [comment]
![image](https://github.com/user-attachments/assets/3439a00c-e660-4516-9424-74b053b4bfe9)
Написал тестовый, костыльный алгоритм, который решает проблему

**Comment by comasqw** [comment]
Упрощённая - 
![image](https://github.com/user-attachments/assets/4ed2f387-983f-45dd-b245-7c3f80769d61)

**Comment by TheShuEd** [comment]
так же:
любит удаленные сущности перезаписывать заного в файл, хотя их нет в игре

![image](https://github.com/user-attachments/assets/e83634cd-74da-4b37-94f0-64b82487e41f)

**Comment by TheShuEd** [comment]
> Упрощённая - ![image](https://private-user-images.githubusercontent.com/138010940/359247997-4ed2f387-983f-45dd-b245-7c3f80769d61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNDE4NzcsIm5iZiI6MTcyNDM0MTU3NywicGF0aCI6Ii8xMzgwMTA5NDAvMzU5MjQ3OTk3LTRlZDJmMzg3LTk4M2YtNDVkZC1iMjQ1LTdjM2Y4MDc2OWQ2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQxNTQ2MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMGJmNDMxOGQ2ZGM0MzM0OWQ3YmVmMzM5ZmE3MzliYjYxYmU0MmQwODk1Y2EzOGM5OGMzMTZmMjBhOGEzMzI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IqYo3-aBw5WsbW_FuHAjocIDGJp44LNkcuJ7s1nZ88E)

а можно в формате пра или хотя бы кода? перепечатывать с скрина такое себе удовольствие...

**Comment by comasqw** [comment]
> > Упрощённая - ![image](https://private-user-images.githubusercontent.com/138010940/359247997-4ed2f387-983f-45dd-b245-7c3f80769d61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNDE4NzcsIm5iZiI6MTcyNDM0MTU3NywicGF0aCI6Ii8xMzgwMTA5NDAvMzU5MjQ3OTk3LTRlZDJmMzg3LTk4M2YtNDVkZC1iMjQ1LTdjM2Y4MDc2OWQ2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQxNTQ2MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMGJmNDMxOGQ2ZGM0MzM0OWQ3YmVmMzM5ZmE3MzliYjYxYmU0MmQwODk1Y2EzOGM5OGMzMTZmMjBhOGEzMzI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IqYo3-aBw5WsbW_FuHAjocIDGJp44LNkcuJ7s1nZ88E)
> 
> а можно в формате пра или хотя бы кода? перепечатывать с скрина такое себе удовольствие...

Сегодня будет

**Comment by comasqw** [comment]
> так же: любит удаленные сущности перезаписывать заного в файл, хотя их нет в игре
> 
> ![image](https://private-user-images.githubusercontent.com/96445749/360538425-e83634cd-74da-4b37-94f0-64b82487e41f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NjgyMjIsIm5iZiI6MTcyNDY2NzkyMiwicGF0aCI6Ii85NjQ0NTc0OS8zNjA1Mzg0MjUtZTgzNjM0Y2QtNzRkYS00YjM3LTk0ZjAtNjRiODI0ODdlNDFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDEwMjUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MmVlOGZiODEzY2I0YTBjODE0M2ZjOTBmMGMyNWFjMzU5ZDM2YTFjNGNkZjRkMmU5MzAwN2MyOTE2NzA1YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZGr-f-ppJj9qbLOG0hvXg2sDrkGcX1W7p-BLSGuljO4)

Это из-за того, что когда ты удаляешь прототип из yml, он всё ещё остаётся в ftl-е, вечером залью проверку в пр с адпейтом.
