### ISSUE TITLE
Набор игровых ролей и департаментов

### ISSUE THREAD

**Issue by TheShuEd** [crystallpunk-14/crystall-punk-14#33]
Необходимо дать базовый набор ролей для MVP. В базу входит только сервисные роли и роль авантюриста.

- [ ] Авантюристы
- [ ] Сервис
  - [ ] Трактирщик
  - [ ] Повар
  - [ ] Горничные
  - [ ] Некий глава сервиса  
- [ ] Стартовая экипировка для ролей

- [ ] Нейминг продумать

**Comment by TheShuEd** [comment]
Да, думаю это будет какая-то прислуга, или что-то другое. Нужно отразить дух днд

**Comment by TheShuEd** [comment]
миссклик

**Comment by Deserty0** [comment]
> Может горничных заменить на Слуг? А то горничная Вася... А глава среди сервиса если взять иерархию слуг, это Управляющий. Хотя в ДнД может быть по другому.

Дворецкие :trollface:

**Comment by hlaji** [comment]
> Необходимо дать базовый набор ролей для MVP. В базу входит только сервисные роли и роль авантюриста.
> 
> * [ ]  Авантюристы
> * [ ]  Сервис
>   
>   * [ ]  Трактирщик
>   * [ ]  Повар
>   * [ ]  Горничные
>   * [ ]  Некий глава сервиса
> * [ ]  Стартовая экипировка для ролей
> * [ ]  Нейминг продумать

**Comment by hlaji** [comment]
может "сервис" переделать просто в "трактир" а главу назвать например "Управляющий трактира"?
