### ISSUE TITLE
personal signatures

### ISSUE THREAD

**Issue by TheShuEd** [crystallpunk-14/crystall-punk-14#364]
Need a mechanic where any player can sign a piece of paper with their signature. This should work like a stamp: a nice inscription with the player's full name, with a prohibition to edit anything on the paper further.
Ideally it should be a nice italic font, but a standard staple visual will do for MVPs as well

необходима механика, когда любой игрок может подписать лист бумаги своей подписью. Это должно работать как штамп: красивая надпись с полным именем игрока, с запретом что-либо редактировать на бумаге далее.
в идеале это должен быть красивый курсивный шрифт, но для MVP подойдет и стандартный визуал штапма

**Comment by Tornado-Technology** [comment]
Как должна определятся его подпись?

**Comment by TheShuEd** [comment]
Браться имя и фамилия из профиля

**Comment by c4llv07e** [comment]
А если имя игрока измениться? Или пока не думать об этом?

**Comment by TheShuEd** [comment]
А как оно может измениться?

**Comment by c4llv07e** [comment]
> А как оно может измениться?

Админ изменит по любой причине, несколько вариантов респавна, какое-нибудь зелье (полиморфа, например) и т.д. В этой игре слишком много возможностей для такого.

**Comment by Tornado-Technology** [comment]
> А как оно может измениться?

Маски скрытия личности меняют имя сущности

**Comment by Tornado-Technology** [comment]
> Браться имя и фамилия из профиля

Существо может иметь руки, существо может не быть игроком

**Comment by TheShuEd** [comment]
смена имени, личности не должна менять подпись. Подпись уникальна и неповторима для игрока, не зависимо от его личины.
