### ISSUE TITLE
CP14WorldEdgeComponent is not working properly with 120 range

### ISSUE THREAD

**Issue by JerryImMouse** [crystallpunk-14/crystall-punk-14#379]
## Description

World bounding works with 30 range, but not with 120, physics just do not raise StartCollideEvent.
Idk what could cause this, probably some chunk stuff or something

**Reproduction**

Set range = 120 in map prototype and try to leave bounding

**Comment by Tornado-Technology** [comment]
Lmao

**Comment by TheShuEd** [comment]
fixed
