### ISSUE TITLE
Workbench UI dont work with { ent-PROTO.name } ftl strings

### ISSUE THREAD

**Issue by TheShuEd** [crystallpunk-14/crystall-punk-14#422]
![image](https://github.com/user-attachments/assets/3179c0cd-21f5-4013-b8ff-f743a6514cfc)

**Comment by FireNameFN** [comment]
Так они так и подписаны в файлах.

Resources\Locale\ru-RU\_CP14\_PROTO\entities\entities.ftl
![image](https://github.com/user-attachments/assets/14789888-22d3-4c5c-a575-f6d7b9062fde)

А с теми предметами, которые подписаны нормально, верстаки работают.

**Comment by TheShuEd** [comment]
в FTL файлах таким образом пишутся линки на описания или названия других предметов, во избежание дубликата названий и локализации

**Comment by TheShuEd** [comment]
В самой игре эти объекты имеют нормальное описание

**Comment by FireNameFN** [comment]
![image](https://github.com/user-attachments/assets/368b4119-dede-4436-969f-72273aa2bf80)
![image](https://github.com/user-attachments/assets/9ee615c4-3a8b-431d-a72a-2abb85a9543a)
![image](https://github.com/user-attachments/assets/579bd9ef-f687-43de-bb26-98937db54a48)

У них нигде не написано описание.



> В самой игре эти объекты имеют нормальное описание

Не имеют.

**Comment by TheShuEd** [comment]
А о, упс
