### ISSUE TITLE
Минимально играбельный продукт

### ISSUE THREAD

**Issue by TheShuEd** [crystallpunk-14/crystall-punk-14#46]
- Лобби
  - [x] Арт для лобби
  - [x] #47
- Апдейт одежды и аксессуаров
  - [x] #48
  - [x] #81
  - [ ] #82
- Апдейт оружия
  - [ ] #35 
- Игровой цикл
- Роли, отделы, геймплей
- [x] #65
- [x] #58

**Comment by Deserty0** [comment]
Исследовати 🙂

**Comment by TheShuEd** [comment]
need restruct
