### ISSUE TITLE
Wrong direction at the mirrored door

### ISSUE THREAD

**Issue by Jaraten** [crystallpunk-14/crystall-punk-14#463]
The mirrored version of the door is put in the wrong direction.
![image](https://github.com/user-attachments/assets/8be8ec02-c009-4e6c-a440-cb2ca2c76b1c)
![image](https://github.com/user-attachments/assets/31b976c4-5200-4e70-b62c-2c110644cd28)

**Comment by TheShuEd** [comment]
Just finish construction
