### ISSUE TITLE
Каменная пещерная стена и белая булыжниковая стена руин: устаревший формат спрайта

### ISSUE THREAD

**Issue by TheShuEd** [crystallpunk-14/crystall-punk-14#69]
Здесь мы приподняли стены:
https://github.com/crystallpunk-14/crystall-punk-14/pull/68

И это стало новым стандартом.

2 указанные стенки необходимо так же приподнять.

**Comment by Agoichi** [comment]
Просьба не удалять пока старые спрайты стен

**Comment by TheShuEd** [comment]
Можешь тут расписать почему?

**Comment by Agoichi** [comment]
В плане делать новые стены делать нужно да. Просто оставьте старые спрайты стен не удаляя их.

> Можешь тут расписать почему?

**Comment by Agoichi** [comment]
Я уже писал тебе для чего

**Comment by TheShuEd** [comment]
Я знаю что ты расписывал в дискорде, я прошу описать в гитхабе, чтобы оно не терялось, и любой мог быстро понять твою точку зрения.

**Comment by Agoichi** [comment]
Спрайты старых стен можно использовать наподобии полублоков как в майнкрафте. Тоесть дефакто старые стены это половинна новых стен.
Вот в чем фишка старых стен
- можно седалть так чтобы они не закрывали обзор
- На них можно было залазить как на столы и стойки
- Использовать их в декоративных целях
