### ISSUE TITLE
Изучить PseudoItem, портированные с фронтира

### ISSUE THREAD

**Issue by TheShuEd** [crystallpunk-14/crystall-punk-14#72]
Эта система судя по всему позволяет класть некоторых больших существ в инвентари, и даже позволяет спать внутри некоторых инвентарей.

Нужно проверить как это работает, и добавить необходимые компоненты на необходимые сущности.

Изучить тэг PreventLabel

**Comment by Tornado-Technology** [comment]
Это пиздец.
Одумайся дважды

**Comment by Deserty0** [comment]
> Это пиздец.
> Одумайся дважды

Мне теперь интересно что там, я пошёл разбираться

**Comment by TheShuEd** [comment]
Мне тоже...
